#!/bin/bash

# Obliviousgmn, April 2015
# https://github.com/ObliviousGmn
# Backup - Dropbox - Usb 

clear
. Colors 

# Variables 
BKUP="Backup_$(date +%m_%Y).tar"
DROPOFF1="$HOME/Dropbox/Backups"
DROPOFF2="$HOME/.usbstick/Backups"
USBSTK="$HOME/.usbstick"
BACKTMP="Backup"

# Prints Filename & Date
printf " ${Green}${0##*/} %85s $(date +%I:%M)${Reset} \n\n"

progress(){
	for ((i = 0; i < $1; i++)); do printf "${Black}.${Reset}"; sleep 0.02; \
		done; printf " ${Blue}[${Reset} COMPLETE ${Blue}]${Reset} \n" ;
}

MKDIRS(){
  printf "  Organizing Files "
  mkdir $BACKTMP
  mkdir $BACKTMP/Home
  mkdir $BACKTMP/Config
  mkdir $BACKTMP/Ncmpcpp
  mkdir $BACKTMP/Weechat
  mkdir $BACKTMP/Root
  mkdir $BACKTMP/Torrent
  mkdir $BACKTMP/Netctl
  mkdir $BACKTMP/2bwm  

  cp $HOME/.xinitrc $BACKTMP/Home
  cp $HOME/.Xdefaults $BACKTMP/Home
  cp $HOME/.bashrc $BACKTMP/Home
  cp -ar $HOME/.fonts $BACKTMP/Home
  
  cp /etc/vimrc $BACKTMP/Root
  cp /etc/hosts.local $BACKTMP/Root
  cp /etc/netctl/Gmnbox $BACKTMP/Netctl

  cp -ar $HOME/Gmnbox $BACKTMP
  cp -ar $HOME/.config/luakit $BACKTMP/Config
  cp -ar $HOME/.config/ranger $BACKTMP/Config
  cp -ar $HOME/.config/htop $BACKTMP/Config
  cp -ar $HOME/.config/youtube-viewer $BACKTMP/Config 
  cp -ar $HOME/.config/sxhkd $BACKTMP/Config

  cp $HOME/.config/mpd/mpd.conf $BACKTMP/Ncmpcpp
  cp -ar $HOME/Media/Music/Radio $BACKTMP/Ncmpcpp
  cp $HOME/.ncmpcpp/config $BACKTMP/Ncmpcpp
  
  cp $HOME/.config/transmission-daemon/settings.json $BACKTMP/Torrent
  cp $HOME/.weechat/weechat.conf $BACKTMP/Weechat
  cp $HOME/.weechat/irc.conf $BACKTMP/Weechat
  cp $HOME/.local/share/luakit/bookmarks.db $BACKTMP/Config/luakit
  cp $HOME/.Source/2bwm/config.h $BACKTMP/2bwm 
  progress 66
}

MKPKG(){
  printf "  Zipping Folder "
  tar cf $BKUP $BACKTMP;
  progress 68
}

USBCHK(){
 if [ $(mount | grep -c ${USBSTK}) != 1 ]; then
   printf " Not mounted "
   echo
   exit 0
   fi	   
}

DROPDB(){
  printf "  Cleaning up "
  mv $BKUP $DROPOFF1
  rm -r $BACKTMP
  progress 71
  echo
}

DROPUSB(){
  printf "  Cleaning up "
  mv $BKUP $DROPOFF2
  rm -r $BACKTMP
  progress 71
  echo
}

USAGE(){
  echo " Backup [ -u Usb | -d Dropbox ] "
  echo
}

case $1 in

  -u|usb|USB) 
	USBCHK
	MKDIRS
	MKPKG 
	DROPUSB ;;

  -d|dropbox) 
	MKDIRS
    	MKPKG
	DROPDB ;;

  *) 
	USAGE ;;
esac

