#!/bin/bash    
# ObliviousGmn  April 2015
# Backups For Dropbox

clear
. Colors

# Prints Filename & Date
printf " ${Color1}${0##*/} %85s $(date +%l:%M)${Reset} \n" 
echo

# Useless magic trick

progress () {
	 for ((i = 0; i < $1; i++)); do printf "${Color0}.${Reset}"; sleep 0.02; \
	 done; printf " ${Color4}[${Reset} COMPLETE ${Color4}]${Reset} \n" ;
}

# Shortcuts
 Bkup="Backup_$(date +%m_%Y).tar"
 Dropoff="$HOME/Dropbox/Backups"

printf "  Organizing Files " 

# Add Folders to make it neater
 mkdir Backup
 mkdir Backup/Home
 mkdir Backup/Config
 mkdir Backup/Ncmpcpp
 mkdir Backup/Weechat
 mkdir Backup/Root
 mkdir Backup/Torrent
 mkdir Backup/Netctl
 mkdir Backup/2bwm

# Home dot files
 cp $HOME/.xinitrc Backup/Home
 cp $HOME/.Xdefaults Backup/Home
 cp $HOME/.bashrc Backup/Home
 cp -ar $HOME/.fonts Backup/Home

# Root Files
 cp /etc/vimrc Backup/Root
 cp /etc/hosts.local Backup/Root
 cp /etc/netctl/Gmnbox Backup/Netctl

# Configs
 cp -ar $HOME/Gmnbox Backup
 cp -ar $HOME/.config/luakit Backup/Config
 cp -ar $HOME/.config/openbox Backup/Config
 cp -ar $HOME/.config/ranger Backup/Config
 cp -ar $HOME/.config/tint2 Backup/Config
 cp -ar $HOME/.config/htop Backup/Config
 cp -ar $HOME/.config/youtube-viewer Backup/Config
# -- 
 cp -ar $HOME/Media/Music/Radio Backup/Ncmpcpp
# --
 cp $HOME/.ncmpcpp/config Backup/Ncmpcpp
 cp $HOME/.config/transmission-daemon/settings.json Backup/Torrent
 cp $HOME/.weechat/weechat.conf Backup/Weechat
 cp $HOME/.weechat/irc.conf Backup/Weechat
 cp $HOME/.local/share/luakit/bookmarks.db Backup/Config/luakit
 cp $HOME/.Source/2bwm/config.h Backup/2bwm
progress 66

# The Action

printf "  Zipping Folder " 

 tar cf ${Bkup} Backup;

progress 68

printf "  Cleaning up " 

 rm -r Backup/
 mv ${Bkup} ${Dropoff};

progress 71
echo

# End of File
