#!/bin/bash
# ObliviousGmn, June 2014
# Master Settings 
# Quick edits

Edit() {
	case $1 in
		alias)		vim ~/Gmnbox/Bin/alias ;;
		edit)		vim ~/Gmnbox/Bin/Edit ;;
		bashrc)		vim ~/.bashrc ;;
		xinitrc)	vim ~/.xinitrc ;;
		xdefaults)	vim ~/.Xdefaults ;;
		notes)		vim ~/Gmnbox/Notes ;;
		*)		echo "You should probably add it idiot!!!" ;;
	esac
}

Conf() {
	case $1 in
		panel)		vim $HOME/Gmnbox/Panel/panel ;;
		barconf)	vim $HOME/Gmnbox/Panel/bar_config ;;
		hostupd)	vim $HOME/Gmnbox/Bin/Hostupd ;;
		backup)		vim $HOME/Gmnbox/Bin/Backup ;;
		usbkp)		vim $HOME/Gmnbox/Bin/Usbkp ;;
		lemonpop)	vim $HOME/Gmnbox/Bin/Lemonpop ;;
		alert)		vim $HOME/Gmnbox/Bin/Alertpp ;;
		temp)		vim $HOME/Gmnbox/Bin/Template ;;
		*)		echo "No config by that name, Dumbass.";;
	esac
}
