#!/bin/sh

# Obliviousgmn, May 2015
# https://github.com/ObliviousGmn
# Lemonpop, Lemon scented popup bar.
# Thanks to z3bra for the idea!

. $HOME/Gmnbox/Panel/bar_config
Setup="-g ${LW}x${LH}+${LX}+${LY} -f ${FONT1} -f ${FONT2} -f ${FONT4} -B ${BG} -F ${FG} -d"
Click="while read line; do eval "$line"; done"

# The Action
case $1 in

	-l) # Longer duration option ..
	shift
	(echo -e "%{F$YELLOW}%{c}$@"; sleep ${ZZZ}) | lemonbar ${Setup} & 
	;;

	-c) # Clickable option w/ long duration .. 
	shift
	(echo -e "%{F$YELLOW}%{c}$@"; sleep ${ZZZ}) | lemonbar ${Setup} | while read line; do eval "$line"; done &
	;;

	-w) # Quick weather ..
	shift	
	(echo -e "%{F$CYAN}%{c}  %{F-}%{F$YELLOW} $(Weather 10039) "; sleep ${zzz}) | lemonbar ${Setup} &
	;;

	-p) # Plex, I'm lazy..
	shift
	(echo -e "%{F$CYAN}%{c}  %{F-}%{F$YELLOW}Plex $@ "; sleep ${zzz}) | lemonbar ${Setup} &
	;;

	-wee) # Weechat notify ..
	aplay -q $HOME/Gmnbox/Sounds/alarm.wav & 

	 POPW="$(($(echo "  $@ " | wc -m) * 6))"
	 POPL="$((1910 - POPW))"

	shift
	(echo -e "%{F$CYAN}%{c}%{F-}%{F$YELLOW} $@"; sleep 6) | 
	lemonbar -g ${POPW}x${LH}+${POPL}+${LY} -f $FONT1 -f $FONT2 -f $FONT4 -B $BG -F $FG &
	;;

	*) # Default option ..
	(echo -e "%{F$YELLOW}%{c}$@"; sleep ${zzz}) | lemonbar ${Setup} &
	;;

esac

