#!/bin/bash
# Lemonbar Setup 
# April 2015

. $HOME/Gmnbox/Panel/bar_config

function panel {

	ws() {
	ws=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')
		echo "${ws}"
	}

	menu() {
		echo "%{B$CYAN}%{F$BG} GMN  %{B-}%{F-}"
	}

	temp() {
	temp=$(sensors | awk '/Core 0/ {print +$3}')
		echo "%{B$BG}%{F$CYAN}  %{B-}%{F-}%{F$YELLOW} ${temp}"
	}
	
	fan(){
	fan=$(sensors | awk '/fan1/ {print +$2}')
		echo "%{B$BG}%{F$CYAN}  %{B-}%{F-}%{F$YELLOW} ${fan} RPM"
	}

	clock() {
	clock=$(date "+%b %d %Y %I:%M")
		echo "%{B$BG}%{F$CYAN}  %{B-}%{F-}%{F$YELLOW} ${clock}"
	}

	vol() {
	vol=$(amixer get Master | sed -nr '$ s:.*\[(.+%)].*:\1:p')
		echo "%{B$BG}%{F$CYAN}  %{B-}%{F-}%{F$YELLOW} ${vol}"
	}

	mus() {
	mus=$(ncmpcpp --now-playing)
	if [[ $mus ]]; then
		echo "%{B$BG}%{F$CYAN}  %{B-}%{F-}%{F$YELLOW} ${mus}"
	else
		echo
	fi
	return 
	}
	
	netstate() {
    	test -n "`ip route`" && echo "Connected" || echo "Disconnected"
	}


	echo " $(ws) $(menu) $(vol) %{c}$(mus) %{r}$(temp) $(fan) $(clock) "
 
}

while true 
 do
		echo "$(panel)"
         sleep 0.5	
 done | lemonbar -g 1900x26+10+10 -f "$FONT1","$FONT2" -B "$BG" -F "$FG" -p &

