#!/bin/sh

# ObliviousGmn, May 2015
# https://github.com/ObliviousGmn
# Panel for Lemonbar..

. $HOME/Gmnbox/Panel/bar_config

 ws(){
  ws=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')
	echo "%{F$YELLOW}${ws}"
}

 menu(){
	echo "%{B$BLUE}%{F$BG} GMN  %{B-}%{F-}"
}

 temp(){
  temp=$(sensors | awk '/Core 0/ {print +$3}')
	echo "%{F$BLUE}  %{F-}%{F$YELLOW} ${temp}"
}
	
 fan(){
  fan=$(sensors | awk '/fan1/ {print +$2}')
	echo "%{F$BLUE}  %{F-}%{F$YELLOW} ${fan} RPM"
}

 clock(){
  clock=$(date "+%b %d %Y %I:%M")
	echo "%{F$BLUE}  %{F-}%{F$YELLOW} ${clock}"
}

 vol(){
  vol=$(amixer get Master | awk '/Mono:/ {print $4}' | tr -d '[]%,')
  switch=$(amixer get Master | awk '/Mono:/ {print $6}')

  if [ "$switch" = "[on]" ]; then
	echo "%{F$BLUE}  %{F-}%{F$YELLOW} ${vol}"
  else
	echo "%{F$RED}  %{F-}%{F$YELLOW} MUTE"
  fi
}

 mus(){
  mus=$(ncmpcpp --now-playing)

 if [[ $mus ]]; then
	echo "%{F$BLUE}  %{F-}%{F$YELLOW} ${mus}"
 else
	echo
 fi
}

# netstate(){
#  test -n "`ip route`" && echo "Connected" || echo "Disconnected"
#}

while :; do 	
	 echo " $(ws) $(menu) $(vol) %{c}$(mus) %{r}$(temp) $(fan) $(clock) "
         sleep 0.5	
 done | lemonbar -g ${PW}x${PH}+${PX}+${PY} -f "$FONT1","$FONT2" -B "$BG" -F "$FG" -p & 

